name: Deploy The-one-parking-bo
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t otakuict/mark-test-fe  .
      - name: Publish Image to docker hub
        run: docker push otakuict/mark-test-fe:latest
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull otakuict/mark-test-fe:latest
      - name: Delete old container
        run: docker rm -f The-one-parking-bo-container
      - name: Run Docker Container
        run: docker run -d -p 3002:3002 --name The-one-parking-bo-container  otakuict/mark-test-fe
