name: Deploy The-one-parking-bo
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: "Create env file"
        run: |
          touch .env
          echo NEXT_PUBLIC_API_BASE_URL=${{ secrets.NEXT_PUBLIC_API_BASE_URL }} >> .env
          echo NEXT_PUBLIC_AUTH_TOKEN_STORAGE_KEY=${{ secrets.NEXT_PUBLIC_AUTH_TOKEN_STORAGE_KEY }} >> .env
          cat .env
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -f Dockerfile.prod -t theoneparking/back-office-fe  .
      - name: Publish Image to docker hub
        run: docker push theoneparking/back-office-fe:latest
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull theoneparking/back-office-fe:latest
      - name: Delete old container
        run: docker rm -f backoffice-theone-container
      - name: Run Docker Container
        run: docker run --restart=always -d -p 3004:3004 --name backoffice-theone-container  theoneparking/back-office-fe
